config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :tasks
  # get "tasks", to: "tasks#index", as: :tasks
  # get "tasks/new", to: "tasks#new", as: :create
  # get "tasks/:id", to: "tasks#display", as: :task

  # get "tasks/:id/edit", to: "tasks#edit", as: :edit
  # patch "tasks/:id", to: "tasks#update"

  # post "tasks", to: "tasks#create"

  # delete "tasks/:id", to: "tasks#destroy", as: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def get_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |t| %>
<div>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <% unless t.object.new_record? %>
    <%= t.label :completed %>
    <%= t.check_box :completed %>
  <% end %>
  <%= t.submit %>
</div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
  <% @tasks.each do |t| %>
  <p>
      <% if t.completed%>
        <i class="fa-regular fa-square-check"></i>
      <% else %>
        <i class="fa-regular fa-square"></i>
      <% end %>
    <%= link_to t.title, task_path(t) %>
  </p>
<% end %>
<p><%= link_to "Create task", new_task_path %></p>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1>Task details</h1>
<h2><%= @task.title %></h2>
<div class="d-flex gap-1">
  <% if @task.completed%>
    <i class="fa-regular fa-square-check"></i><p><%= @task.details %></p>
  <% else %>
    <i class="fa-regular fa-square"></i><p><%= @task.details %></p>
  <% end %>
</div>


<p><%= link_to "Edit task", edit_task_path %></p>
<p><%= link_to "Destroy task", task_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p>
<p><%= link_to "Back to task list", tasks_path %></p>